name: Test

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    name: Run test with ${{ matrix.faraday }} on ruby ${{ matrix.ruby }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: bundle install
        run: |
          bundle install
          bundle exec appraisal install
      - name: Run test
        run: |
          bundle exec appraisal ${{ matrix.faraday }} rspec
